import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createHash } from 'node:crypto';

// Generate a docker-compose.session.yml file with random port bindings
// and dev-prism labels for container discovery
export function generateComposeFile(
  workingDir: string,
  projectName: string,
  services: Array<{
    name: string;
    internalPort: number;
  }>
): string {
  const createdAt = new Date().toISOString();

  // Generate a short hash of the working directory for compose project name
  const dirHash = createHash('md5').update(workingDir).digest('hex').substring(0, 8);
  const composeProjectName = `${projectName}-${dirHash}`;

  const lines = [
    '# Auto-generated by dev-prism - DO NOT EDIT',
    '',
    'x-dev-prism-labels: &dev-prism-labels',
    '  dev-prism.managed: "true"',
    `  dev-prism.working_dir: "${workingDir}"`,
    `  dev-prism.session_id: "${workingDir}"`,
    `  dev-prism.created_at: "${createdAt}"`,
    '',
    'services:',
  ];

  for (const service of services) {
    lines.push(`  ${service.name}:`);
    lines.push(`    extends:`);
    lines.push(`      file: docker-compose.yml`);
    lines.push(`      service: ${service.name}`);
    lines.push(`    ports:`);
    lines.push(`      - "0:${service.internalPort}"  # Random host port`);
    lines.push(`    labels:`);
    lines.push(`      <<: *dev-prism-labels`);
    lines.push(`      dev-prism.service: "${service.name}"`);
    lines.push(`      dev-prism.internal_port: "${service.internalPort}"`);
    lines.push(``);
  }

  // Add project name as env var
  lines.unshift(`# Compose project name: ${composeProjectName}`);
  lines.unshift('');

  // Add volumes section (extends doesn't inherit top-level volumes)
  lines.push('volumes:');
  lines.push('  postgres-data:');

  return lines.join('\n');
}

// Write docker-compose.session.yml to working directory
export function writeComposeFile(
  workingDir: string,
  projectName: string,
  services: Array<{ name: string; internalPort: number }>
): string {
  const content = generateComposeFile(workingDir, projectName, services);
  const filePath = resolve(workingDir, 'docker-compose.session.yml');
  writeFileSync(filePath, content, 'utf-8');
  return filePath;
}

// Generate .env.session stub for compose project name
export function generateEnvStub(workingDir: string, projectName: string): string {
  const composeProjectName = getComposeProjectName(workingDir, projectName);

  const lines = [
    '# Auto-generated by dev-prism',
    `COMPOSE_PROJECT_NAME=${composeProjectName}`,
    `SESSION_DIR=${workingDir}`,
    '',
    '# Ports will be added after containers start',
  ];

  return lines.join('\n') + '\n';
}

// Get the compose project name with directory hash
export function getComposeProjectName(workingDir: string, projectName: string): string {
  const dirHash = createHash('md5').update(workingDir).digest('hex').substring(0, 8);
  return `${projectName}-${dirHash}`;
}
